name: CI
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.1
      - name: Install dependencies
        run: bundle install
      - name: Run linter
        run: bundle exec rubocop

  release-please:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
      version: ${{ steps.release-please.outputs.version }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release-please

  release:
    runs-on: ubuntu-latest
    needs: [lint, release-please]
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.1
      - name: Export version from tag name
        run: echo "${{ needs.release-please.outputs.version }}" > VERSION
      - name: Build Gem
        run: gem build *.gemspec
      - name: Setup credentials
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}\n" > $HOME/.gem/credentials
        env:
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
      - name: Publish to RubyGems
        run: |
          gem push *.gem
